### ISSUE TITLE
work_mem

### ISSUE THREAD

**Issue by brafaeloliveira** [le0pard/pgtune#17]
Hi! Why does this happen?...

![image](https://user-images.githubusercontent.com/20186904/39629019-b7fc4782-4fa2-11e8-90d9-e4e61de95416.png)

Cheers!

**Comment by le0pard** [comment]
Because before it use [this formula](https://github.com/le0pard/pgtune/blob/270320a4ce495b8405848647a529239d96c26091/source/javascripts/pgtune.coffee#L120), which ignore CPU number.

But after reading of documentation:

> **max_parallel_workers_per_gather** (integer)
> Sets the maximum number of workers that can be started by a single Gather or Gather Merge node. Parallel workers are taken from the pool of processes established by max_worker_processes, limited by max_parallel_workers. Note that the requested number of workers may not actually be available at run time. If this occurs, the plan will run with fewer workers than expected, which may be inefficient. The default value is 2. Setting this value to 0 disables parallel query execution.
> 
> Note that parallel queries may consume very substantially more resources than non-parallel queries, because each worker process is a completely separate process which has roughly the same impact on the system as an additional user session. **This should be taken into account when choosing a value for this setting, as well as when configuring other settings that control resource utilization, such as work_mem. Resource limits such as work_mem are applied individually to each worker, which means the total utilization may be much higher across all processes than it would normally be for any single process. For example, a parallel query using 4 workers may use up to 5 times as much CPU time, memory, I/O bandwidth, and so forth as a query which uses no workers at all.**

Calculation changed to reduce memory by number of `max_parallel_workers_per_gather`. Now it is  calculating by [this formula](https://github.com/le0pard/pgtune/blob/master/webpack/selectors/configuration.js#L272) 

Old value can lead to work_mem out of memory issue with parallel queries.

Hope now all clear.

**Comment by brafaeloliveira** [comment]
Ok, thank you so much!
