### ISSUE TITLE
Feedback from HN

### ISSUE THREAD

**Issue by rrjanbiah** [le0pard/pgtune#35]
I'm sorry... I'm not good enough in Postgres to comment. But, below comment is found in HN:

> The suggestions pgtune makes are really bad. It sets max_wal_size way too low, max_parallel_workers_per_gather to ridiculously high values, shared_buffers way too low, the work_mem settings make no sense whatsoever.

https://news.ycombinator.com/item?id=22219283

If anything can be improved based on above comment, it will be good.

**Comment by le0pard** [comment]
@rrjanbiah thanks for information, but based on this comment I cannot improve anything in pgtune. 

Author of this comment didn't provide information, why some of this values need to be higher or lower and add mathematical model with database performance tests, which prove his words. Looks like just for his "special case" was needed changes, which not similar for pgtune (because pgtune know only hardware, not know how used database and what kind of data it contain).

Sorry, but this is just useless information for improvements.

**Comment by le0pard** [comment]
@rrjanbiah 

BTW, pgtune is open source tool. So if author know how to improve it - PR are welcome. Just some comment on HN not improve it for everyone.

**Comment by anarazel** [comment]
Hi,

I didn't intend the comment to be a bug report. So it's not surprising that it's not detailed enough for one. Somebody mentioned pgtune in the context of what can be tuned, and I looked at the results for a few example workloads, and they were bad. So I said that. 

I don't think me saying that I don't think the recommendations are good when somebody brings it up somehow translates into an obligation that I ought to provide patches to make pgtune better.


> Author of this comment didn't provide information, why some of this values need to be higher or lower and add mathematical model with database performance tests, which prove his words. Looks like it is just his "special case", which not similar for pgtune (because pgtune know only hardware, do not know how use database and what kind of data it contain).

No, it's not just my special case.  A good portion of the recommended settings are just not good. 

> (because pgtune know only hardware, do not know how use database and what kind of data it contain).

That's a *problem*. It doesn't make sense to tune a database without any awareness of that.


Example 1:
```# DB Version: 12
# OS Type: linux
# DB Type: oltp
# Total Memory (RAM): 64 GB
# CPUs num: 40
# Connections num: 150
# Data Storage: ssd
```

```
shared_buffers = 16GB
```
This looks like 25% of mem. Often close to the the *worst* possible shared_buffers setting (which is often around 30-35%). For databases that are small, you're wasting memory. For larger databases you'll end up with nearly complete double buffering, and thus a lower overall cache hit ratio. With a smaller s_b you end up with the OS doing most of the caching - higher overall cache hit ratio. With a  larger s_b you end up with postgres doing most of the caching - higher overall cache hit ratio, with fewer memory copies.  And yes, I've run benchmarks for this (https://twitter.com/AndresFreundTec/status/1178765225895399424 among others). On an OLTP setup you're not going to otherwise require huge amounts of memory, leaving a few autovacuum processes aside.

And if you were optimizing for a workload that does frequent truncations/table dropping, where large shared buffers hurts, the setting is way too large.

``
checkpoint_completion_target = 0.9
wal_buffers = 16MB
min_wal_size = 2GB
max_wal_size = 4GB
```
For a larger system a max_wal_size is a bad recommendation - it is very easy to generate more WAL in 5 minutes, which means that your checkpoints will occur more frequently. Leading to spikey latency, and inefficient use of hard

Not quite as crucial (for OLTP, more important for workloads with more bulk loads and less frequent WAL flushes), but wal_buffers = 16MB is too small for any moderately heavy workload - there more often will be contention on the locks protecting wal_buffers. That happens whenever 

```
effective_io_concurrency = 200
```
For an OLTP system this is really high. This means that a bitmap heap scan might issue a lot of concurrent IO - which will lead to writes slowing down quite tremendously: A WAL flush (e.g. for a commit) will take longer to be executed, holding up all concurrent commits.

```
max_worker_processes = 40
max_parallel_workers_per_gather = 20
max_parallel_workers = 40
```
There's pretty much never a good reason to allow a single query 20 workers for parallelism. And definitely not in an OLTP workload. And even workloads benefiting from parallelism: With 40 configured workers, this means that you'd potentially prevent the third concurrent query from getting any workers.

Switching the above hardware to a warehouse, with 20 concurrent sessions allowed I get:
```
work_mem = 20971kB
```
which is very likely too small for any realistic warehousing workload. Being able to do hashjoins, hashaggs, sorts with larger amounts of memory often is very crucial for that.


I think to start to be able to actually provide useful hints what settings to change you'd at the very least need to inquire what the size of the database is roughly going to be. Without that there's just no way to actually give useful advice.

For any workload with a number of active connections, and with 

What's the reasoning behind web workloads suggesting
```
checkpoint_completion_target = 0.7
```
? I'm just curious why the suggestion is different for this specific workload?

Regards,

Andres

**Comment by rrjanbiah** [comment]
@anarazel Thanks for sharing constructive comments. I think, both of you're are Postgres core committers. So, hopefully `pgtune` will become much usable than what it currently does. (And, I'm greatly depend on it). 

Thank you both of you @anarazel @le0pard

**Comment by le0pard** [comment]
Thanks for information @anarazel

So first of all, pgtune should be not create harm for user database tuning ([Primum non nocere](https://en.wikipedia.org/wiki/Primum_non_nocere)). Due to limited number of information, it cannot tune your PostgreSQL instance for maximum performance. So even if "tuning parameter" questionable or works only in special conditions, it cannot propose it in the end, because it unsafe for all other users.

> This looks like 25% of mem. Often close to the the worst possible shared_buffers setting (which is often around 30-35%). For databases that are small, you're wasting memory. For larger databases you'll end up with nearly complete double buffering, and thus a lower overall cache hit ratio. With a smaller s_b you end up with the OS doing most of the caching - higher overall cache hit ratio. With a larger s_b you end up with postgres doing most of the caching - higher overall cache hit ratio, with fewer memory copies. And yes, I've run benchmarks for this (https://twitter.com/AndresFreundTec/status/1178765225895399424 among others). On an OLTP setup you're not going to otherwise require huge amounts of memory, leaving a few autovacuum processes aside.

I think this need to be proven by some benchmarks. We know, that pgtune will not know of a size of user database, tables and SQL queries. So we need to prove practically, that for the same condition `30-35%` will be better, than `25%`. Especially if 25% is reasonable starting point for tuning, even mentioned in docs - https://www.postgresql.org/docs/current/runtime-config-resource.html#RUNTIME-CONFIG-RESOURCE-MEMORY PostgreSQL RDS databases also use 25% for `shared_buffers`.

> For a larger system a max_wal_size is a bad recommendation - it is very easy to generate more WAL in 5 minutes, which means that your checkpoints will occur more frequently. Leading to spikey latency, and inefficient use of hard

Again, this doesn't depend from hardware, only from system itself, which use database. Also big `max_wal_size`, which user not expected to provide for database. But even in this case, what amount `max_wal_size` should have `oltp` by your "generate more WAL in 5 minutes" case?

> Not quite as crucial (for OLTP, more important for workloads with more bulk loads and less frequent WAL flushes), but wal_buffers = 16MB is too small for any moderately heavy workload - there more often will be contention on the locks protecting wal_buffers.

Lets go to official doc - https://www.postgresql.org/docs/current/runtime-config-wal.html 

"The amount of shared memory used for WAL data that has not yet been written to disk. The default setting of -1 selects a size equal to 1/32nd (about 3%) of shared_buffers, but not less than 64kB **nor more than the size of one WAL segment, typically 16MB**"

Again, we need benchmarks to prove words and debunk wrong documentation. User (maybe) will see some benefits, if he also change WAL segment size, but this can be done only by compilation process (`--with-wal-segsize` from PG 11). PGTune do not "propose" this stuff.

> effective_io_concurrency = 200
> For an OLTP system this is really high. This means that a bitmap heap scan might issue a lot of concurrent IO - which will lead to writes slowing down quite tremendously: A WAL flush (e.g. for a commit) will take longer to be executed, holding up all concurrent commits.

Here some link about usage SSD and PostgreSQL:
https://dev.to/pythonmeister/basic-postgresql-tuning-parameters-281
https://portavita.github.io/2019-07-19-PostgreSQL_effective_io_concurrency_benchmarked/
[https://github.com/le0pard/pgtune/issues/10](https://github.com/le0pard/pgtune/issues/10)

But again, ready for your benchmarks - I am open minded about this.

> max_worker_processes = 40
> max_parallel_workers_per_gather = 20
> max_parallel_workers = 40
> There's pretty much never a good reason to allow a single query 20 workers for parallelism. And definitely not in an OLTP workload. And even workloads benefiting from parallelism: With 40 configured workers, this means that you'd potentially prevent the third concurrent query from getting any workers.

PostgreSQL not "so stupid" to provide any request all proposed 20 workers. I provided more info here

https://github.com/le0pard/pgtune/pull/23#issuecomment-491838366

BTW, by this link authors also show that benefits from more workers exist, but it can be not so sufficient, if you need this CPU for something else.

But I am ok to change this value to some another math model (like, more than 4 `max_parallel_workers_per_gather` is not have benefits). Current is `CPU / 2`.

> Switching the above hardware to a warehouse, with 20 concurrent sessions allowed I get:
> work_mem = 20971kB
> which is very likely too small for any realistic warehousing workload. Being able to do hashjoins, hashaggs, sorts with larger amounts of memory often is very crucial for that.

It is math. Too many `max_parallel_workers_per_gather` + `connections` reduce amount a `work_mem`.

> I think to start to be able to actually provide useful hints what settings to change you'd at the very least need to inquire what the size of the database is roughly going to be. Without that there's just no way to actually give useful advice.

In this case, we need to create how user will provide size for database (select, input) and how pgtune will calculate parameters. Like different math model with new parameter.

> What's the reasoning behind web workloads suggesting
> checkpoint_completion_target = 0.7

This param migrated from original [pgtune](https://github.com/gregs1104/pgtune)
